---

keycloak_private_tmp: false

# JAVA
java_jdk_vendor: adoptopenjdk
java_open_jdk_version_major: 8

# POSTGRESQL
pg_users:
  - name: keycloak
    password: keycloak

pg_databases:
  - name: keycloak
    owner: keycloak

# Keycloak mode
keycloak_config_file: standalone-ha.xml
keycloak_server_config_file_path: "standalone-ha.xml.j2"

# Keycloak Cache
keycloak_config_realms_cache_enabled: 'false'
keycloak_config_users_cache_enabled: 'false'
keycloak_config_realms_cache_ttl: 6400
keycloak_config_users_cache_ttl: 6400

# Keycloak Credentials
keycloak_admin_user: admin
keycloak_admin_password: admin

# JDBC
keycloak_jdbc_install: true
keycloak_jdbc: postgresql
keycloak_jdbc_jar: postgresql-42.2.18.jar
keycloak_jdbc_file_path: module.xml.j2
keycloak_jdbc_origin: 'url'
keycloak_jdbc_download_url: 'https://jdbc.postgresql.org/download/postgresql-42.2.18.jar'
keycloak_jdbc_module: 'org.postgresql'

# Configuration
keycloak_xa_datasource_class: "org.postgresql.xa.PGXADataSource"
keycloak_db_connection_url: "jdbc:postgresql://localhost:5432/keycloak"
keycloak_db_user: "keycloak"
keycloak_db_password: "keycloak"
keycloak_db_max_pool_size: 20
keycloak_db_validation_sql: select 1
keycloak_db_validation_enabled: true
keycloak_db_validation_ms: 15000

# Keycloak cluster
keycloak_jboss_jgroups_stack: "tcp"
keycloak_jboss_jgroups_tcp_tcpping_enabled: true
keycloak_jboss_jgroups_tcp_tcpping_initial_hosts: "192.168.1.1[7600],192.168.1.2[7600]"
